version: 1.0.{build}
os: Visual Studio 2017
platform: x64
clone_folder: C:\projects\npe
shallow_clone: true
branches:
  only:
    - master
environment:
  matrix:
  - config: Release
    PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6.x" # currently 3.6.8
    PYTHON_ARCH: "64"

  # - config: Debug
  #   PYTHON: "C:\\Python27-x64.exe"
  #   PYTHON_VERSION: "2.7.x" # currently 2.7.15
  #   PYTHON_ARCH: "64"
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install numpy"
  - "python -c \"import numpy as np;import sys;print(np.get_include())\""
  # - "dir C:\\Python36-x64\\lib\\site-packages\\numpy\\core\\include"
  # - "dir C:\\Python36-x64\\lib\\site-packages\\numpy\\core\\include\\numpy"
build:
  parallel: true
build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cd c:\projects\npe
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%config% -G "Visual Studio 15 2017 Win64" -DNPE_PYTHON_EXECUTABLE=python ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%config% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% NumpyEigen.sln

test_script:
  - ctest -C %config% --verbose --output-on-failure -j 2