language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install cmake
env:
  - CC=gcc CXX=g++
#  - CC=clang CXX=clang++
install:
  - pip install scipy
script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make VERBOSE=1
  - make test
