language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="export CC=gcc && CXX=g++ && CONFIG=Release"
  # - os: linux
  #   compiler: clang
  #   env:
  #   - MATRIX_EVAL="export CC=clang && CXX=clang++ && CXXFLAGS=\"-stdlib=libc++\" && CONFIG=Release"
  # - os: osx
  #   osx_image: xcode8.3
  #   compiler: clang
  #   env:
  #   - MATRIX_EVAL="export CONFIG=Release"
addons:
  apt:
    packages:
    - libc++-dev
install:
  - pip install scipy
  - eval "${MATRIX_EVAL}"
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG
  - make VERBOSE=1
  - make test
