language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
    env:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++ CXXFLAGS="-stdlib=libc++"
  # - osx
  #   osx_image: xcode8.3
  #   compiler: clang
addons:
  apt:
    packages:
    - libc++-dev

install:
  - pip install scipy
script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make VERBOSE=1
  - make test
